dist: trusty
language: rust
matrix:
  include:
  - rust: 1.26.0
  - rust: 1.27.0
  - rust: stable
  - rust: beta
  - rust: nightly
cache: cargo
script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features
